---
- name: CCDC Tasks
  hosts: linux
  tasks:
    - name: hostname
      include_tasks: tasks/linux/hostname.yml
      tags:
        - never
        - hostname
    - name: setup_velociraptor
      include_tasks: tasks/linux/setup_velociraptor.yml
      tags:
        - never
        - velociraptor