---
- name: "Copy SSH keys to all hosts"
  hosts: all
  become: yes
  vars:
    ssh_key_path: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
    - name: "Ensure the .ssh directory exists on the target with u+rwx permissions"
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "Copy the SSH public key to authorized_keys"
      ansible.builtin.copy:
        content: "{{ ssh_key_path }}"
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      register: copy_result

    - name: "Print success message"
      debug:
        msg: "SSH key successfully copied to {{ inventory_hostname }}"
      when: copy_result.changed
