---
- name: Gather system information
  hosts: all
  tasks:
    - name: Get date
      delegate_to: localhost
      run_once: true
      command: date
      register: date

    - name: Get hostname
      command: cat /etc/hostname
      register: hostname

    - name: Get kernel version
      command: uname -r
      register: kernel_version

    - name: Get network interfaces
      command: ip addr
      register: ip_addr_info

    - name: Get listening network connections
      command: netstat -tulpn
      register: netstat_info

    - name: Get logged in users
      command: who
      register: who_info

    - name: Get authorized_keys
      command: cat ~/.ssh/authorized_keys
      register: authorized_keys

    - name: Save output to local file
      delegate_to: localhost
      #run_once: true
      copy:
        content: |
          Host: {{ inventory_hostname }} ({{ hostname.stdout }})
          Date: {{ date.stdout }}
          ---------------------------

          $ uname -r
          {{ kernel_version.stdout }}

          ---------------------------

          $ ip addr
          {{ ip_addr_info.stdout }}

          ---------------------------

          $ netstat -tulpn
          {{ netstat_info.stdout }}

          ---------------------------

          $ who
          {{ who_info.stdout }}

          ---------------------------

          $ cat ~/.ssh/authorized_keys
          {{ authorized_keys.stdout }}
        dest: ./system_info_{{ inventory_hostname }}.txt
